import { Engine, Scene } from '@babylonjs/core';
import './style.css';
import { showHomeScreen } from './home';
import { createPlayer } from './player/playerController';
import { buildWorld } from './world/world';
import { setupLighting } from './graphics/lighting';
const canvas=document.querySelector<HTMLCanvasElement>('#game')!;
const engine=new Engine(canvas,true);engine.setHardwareScalingLevel(Math.max(1,window.devicePixelRatio/1.5));
const scene=new Scene(engine);scene.collisionsEnabled=true;
const shadows=setupLighting(scene);buildWorld(scene,shadows);const player=createPlayer(scene,canvas);
const hint=document.getElementById('hint');if(hint)hint.textContent='WASD: move · Shift: sprint · Space: jump · Esc: release mouse';
const stats=document.createElement('div');stats.style.cssText='position:fixed;top:12px;right:12px;z-index:5;color:#eef2df;background:#101810aa;padding:6px 9px;border-radius:3px;font:12px monospace;pointer-events:none';document.body.appendChild(stats);
let elapsed=0;scene.onAfterRenderObservable.add(()=>{elapsed+=engine.getDeltaTime();if(elapsed>500){stats.textContent=Math.round(engine.getFps())+' FPS · forest scene';elapsed=0;}});
showHomeScreen(()=>player.start());engine.runRenderLoop(()=>scene.render());window.addEventListener('resize',()=>engine.resize());
