import { Engine, Scene, Color3, Color4, Vector3, HemisphericLight, DirectionalLight, ShadowGenerator } from '@babylonjs/core';
import './style.css';
import { showHomeScreen } from './home';
import { createPlayer } from './player';
import { buildForest } from './forest';
const canvas=document.querySelector<HTMLCanvasElement>('#game')!;
const engine=new Engine(canvas,true);
engine.setHardwareScalingLevel(Math.max(1,window.devicePixelRatio/1.5));
const scene=new Scene(engine);
scene.clearColor=new Color4(0.60,0.68,0.69,1);scene.collisionsEnabled=true;
scene.fogMode=Scene.FOGMODE_EXP2;scene.fogColor=new Color3(0.60,0.68,0.69);scene.fogDensity=0.006;
const sky=new HemisphericLight('sky',Vector3.Up(),scene);sky.intensity=0.7;
sky.diffuse=new Color3(0.86,0.93,1);sky.groundColor=new Color3(0.28,0.25,0.18);
const sun=new DirectionalLight('sun',new Vector3(-0.6,-1,0.4),scene);
sun.position=new Vector3(35,55,-25);sun.intensity=1.2;sun.diffuse=new Color3(1,0.91,0.77);
sun.shadowMinZ=1;sun.shadowMaxZ=180;
const shadows=new ShadowGenerator(1024,sun);shadows.usePercentageCloserFiltering=true;shadows.bias=0.002;
buildForest(scene,shadows);
const player=createPlayer(scene,canvas);
const hint=document.getElementById('hint');
if(hint)hint.textContent='WASD: move · Shift: sprint · Space: jump · Esc: release mouse';
const stats=document.createElement('div');
stats.style.cssText='position:fixed;top:12px;right:12px;z-index:5;color:#eef2df;background:#101810aa;padding:6px 9px;border-radius:3px;font:12px monospace;pointer-events:none';
document.body.appendChild(stats);
let elapsed=0;
scene.onAfterRenderObservable.add(()=>{
  elapsed+=engine.getDeltaTime();if(elapsed>500){stats.textContent=Math.round(engine.getFps())+' FPS · forest scene';elapsed=0;}
});
showHomeScreen(()=>player.start());
engine.runRenderLoop(()=>scene.render());window.addEventListener('resize',()=>engine.resize());
